### ISSUE TITLE
Main menu sounds

### ISSUE THREAD

**Issue by MadejaMaciej** [niner-games/lost-dutchman-mine#48] opened 2024-03-10 20:02 UTC
@mrfatguy could you extract sounds that we can hear in main menu and loading screen?

**Comment by mrfatguy** [comment] 2024-03-10 20:31
Yes, will do. But, please, keep in mind that main menu's ticket (#14) is still on me, so don't implement this yet.

We're doing a 100% clone, but since there is not graphic mode selection in our clone and since there is a translation system in our version of the game then the main options menu will look completely different than in the original game.

**Comment by mrfatguy** [comment] 2024-03-24 22:35
@MadejaMaciej Can't add audio files directly to the ticket, because GitHub doesn't support it.

I am closing this ticket as kind-of duplicate of #14. I will provide all the details, files etc. to [Wiki](https://github.com/niner-games/lost-dutchman-mine/wiki/Game.-Settings) and to the #14 ticket.

**Closed by mrfatguy** 2024-03-24 22:35 UTC
Labels: assets

**Comment by mrfatguy** [comment] 2024-03-25 10:58
@MadejaMaciej Files [are provided](https://github.com/niner-games/lost-dutchman-mine/wiki/Game.-Settings), as promised:

- [intro-full.mp3](https://github.com/niner-games/lost-dutchman-mine/wiki/audio/settings-tune.mp3) 
- [intro-full.wav](https://github.com/niner-games/lost-dutchman-mine/wiki/audio/settings-tune.wav)

But -- as I said -- they will be part of #14, so please, don't add them until #14 lands on you, ready to be implemented. Thx!
